"""Stage 4 — One-shot LLM judge.

Receives the task, candidate CTL, and execution evidence (pre-fetched by the
runner as text). Returns a structured verdict. No MCP calls — pure LLM.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


# ---------------------------------------------------------------------------
# CTL2 reference — loaded once, prepended to every judge system prompt.
# ---------------------------------------------------------------------------

def _load_ctl2_reference() -> str:
    path = Path(__file__).parent.parent / "resources" / "ctl2-basics.md"
    if not path.exists():
        return ""
    text = path.read_text(encoding="utf-8")
    text = re.sub(r"^---\n.*?---\n+", "", text, flags=re.DOTALL).strip()
    return text


_CTL2_REFERENCE = _load_ctl2_reference()


# ---------------------------------------------------------------------------
# Failure-mode taxonomy — single source of truth for the whole pipeline
# ---------------------------------------------------------------------------

FAILURE_MODES: frozenset[str] = frozenset({
    "wrong_field_assignment",
    "decimal_integer_upcasting",
    "date_format_token",
    "dropped_records_wrong_return",
    "null_propagation",
    "rollup_lifecycle",
    "rollup_accumulator_mismatch",
    "rollup_per_record_emission",
    "rollup_missing_update_transform",
    "filter_inverted_condition",
    "filter_missing_null_guard",
    "filter_off_by_one",
    "join_wrong_port_source",
    "join_key_type_mismatch",
    "join_null_unmatched",
    "normalizer_count_transform_mismatch",
    "normalizer_idx_off_by_one",
    "denormalizer_lifecycle",
    "datagen_wrong_return_code",
    "datagen_record_count_mismatch",
    "sequence_wrong_syntax",
    "lookup_wrong_invocation",
    "wrong_function_name",
    "invalid_cast",
    "other",
})

_FAILURE_MODE_LIST = "\n".join(f"- {m}" for m in sorted(FAILURE_MODES))

# ---------------------------------------------------------------------------
# Verdict dataclass
# ---------------------------------------------------------------------------

@dataclass
class JudgeVerdict:
    verdict: str                          # correct | incorrect | partially_correct
    confidence: float                     # 0.0 – 1.0
    failure_modes: list[str] = field(default_factory=list)
    explanation: str = ""                 # ≤60 words, evidence-grounded
    minimal_fix: str = ""
    exec_level: str = ""                  # propagated from ExecResult for convenience


# ---------------------------------------------------------------------------
# Prompts
# ---------------------------------------------------------------------------

_JUDGE_SYSTEM_BASE = f"""\
You are an expert CTL2 (CloverDX transformation language) code evaluator.

You receive:
  1. The CTL2 task (system prompt + user prompt used for SFT training)
  2. A candidate CTL2 completion generated by a fine-tuned model
  3. Execution evidence from a live CloverDX server run of the candidate

Your job: determine whether the candidate is correct and, if not, classify why.

## Output
Respond with a single raw JSON object — no markdown fences, no prose before or after:
{{
  "verdict": "correct" | "incorrect" | "partially_correct",
  "confidence": <0.0 to 1.0>,
  "failure_modes": [<from the taxonomy below>],
  "explanation": "<≤60 words — cite specific evidence from execution>",
  "minimal_fix": "<optional: shortest change that would fix it, or empty string>"
}}

## Failure mode taxonomy (use exact strings only):
{_FAILURE_MODE_LIST}

## Evaluation priority (apply in order — stop when verdict is determined)

### Priority 1 — Requirement coverage (most important)
Read every business rule stated in the user prompt (field names, data types, value ranges,
rounding, date formats, filtering conditions, join keys, grouping, etc.) and verify that
the CTL code implements ALL of them.
- Missing or wrong implementation of any stated business rule → verdict="incorrect",
  failure_mode="other" (or the matching taxonomy entry if one fits).
- Example: prompt says "amount with 2 decimal places" → code must round or use an
  appropriate type; omitting the rounding is a requirement miss even if the code compiles.
- Partial coverage (most rules correct, one minor rule missed) → "partially_correct".

### Priority 2 — Execution evidence
- exec_level=L3_pass: run succeeded AND output matched golden → supports "correct".
- exec_level=L1_fail: compile/entry-point error → "incorrect".
- exec_level=L2_fail: runtime crash → "incorrect".
- exec_level=L3_mismatch: output differed from golden. Investigate the diff carefully:
  - Real logic error (wrong field, wrong operator, wrong grouping key, etc.) → "incorrect".
  - Candidate adds null-handling (nvl/isnull guard) on a field whose metadata does NOT
    declare `nullable="false"`, or on any $in.1.* field in a LEFT OUTER JOIN → this is
    a valid, often better, alternative. Call it "correct" if all explicit requirements
    are met; extra null safety on a nullable field is not a bug.
  - Candidate uses a semantically EQUIVALENT null-coalescing form that produces different
    output only for null inputs, and the prompt does not specify null behaviour → "correct"
    if all stated requirements are satisfied; the reference is not the only valid answer.
  - Genuine ambiguity where both sides have merit → "partially_correct".
- Never return verdict="correct" for L1_fail or L2_fail.

### Priority 3 — Prose / explanation style (least important)
The expected output from the model is correct CTL code. Explanatory prose around the code
is optional and should only be valued when the user prompt explicitly or implicitly asks for
an explanation (e.g. "explain", "how does", "describe", "with comments").
- DO NOT penalise a candidate for lacking prose.
- DO NOT reward a candidate for having prose if its code is less correct than a prose-free
  alternative. A well-commented wrong answer is still wrong.
- Only let prose style break a tie between two candidates that are equally correct on
  requirements and execution.

## Additional rules
- failure_modes must be evidence-backed: only tag what the log, output_diff, or a concrete
  requirement gap demonstrates — never what you merely suspect from reading the code.
- confidence reflects certainty given evidence quality, not code quality.
- Unknown failure modes → "other".

## Null-handling and metadata
Whether a field can carry null is determined by its metadata declaration:
- Field with NO `nullable` attribute, or `nullable="true"` → the field CAN be null.
  Guarding it with `nvl()` / `isnull()` is correct and often preferable.
- Field with `nullable="false"` → the graph enforces non-null at runtime; null cannot
  legitimately reach the CTL. Adding a null guard is harmless but unnecessary.

Special case — EXT_HASH_JOIN LEFT OUTER JOIN: when the slave (port 1) has no matching
record, ALL `$in.1.*` fields are null at runtime, regardless of what the slave metadata
declares as `nullable`. Null-guarding slave fields in a LEFT OUTER JOIN transform is
therefore ALWAYS correct, even if the slave metadata says `nullable="false"`.

### Null-handling equivalences (do NOT penalise either form)
These patterns are semantically equivalent in CTL2:
- `nvl(x, default)` ≡ `isnull(x) ? default : x`  (null coalescing)
- `nvl2(x, non_null_val, null_val)` ≡ `isnull(x) ? null_val : non_null_val`

### When to flag null_propagation
Tag `null_propagation` ONLY when the candidate:
- Reads a field that CAN be null (no `nullable="false"` in metadata, or a LEFT OUTER JOIN
  slave field) and assigns it directly to an output field without any null guard, AND
- The prompt explicitly requires a default or the missing guard causes the output diff to
  show nulls where values are expected.
Do NOT tag it when the reference itself leaves the same field unguarded, or when the
prompt does not specify behaviour for null inputs on that field.

## EXT_FILTER form
EXT_FILTER CTL is a `//#CTL2` header line followed by a bare boolean expression with NO
function wrapper, e.g.
  `//#CTL2\n$in.0.amount > 100 && $in.0.status == "active"`
- Do NOT penalise a filter candidate for lacking a `function` declaration — the bare
  expression is the correct and expected form.
- The leading `//#CTL2` header IS required: without it CloverDX parses the code as the
  removed CTL1 language and it fails to compile. A header-less candidate is correctly
  reported as exec_level=L1_fail (run_status=MISSING_CTL2_HEADER) → verdict="incorrect".
- Only flag missing-function as wrong_function_name if the code uses a function with an
  unrecognised name that would prevent execution.
"""

_JUDGE_DENORMALIZER_NOTE = """\

## DENORMALIZER component contract

DENORMALIZER accumulates input records into one output row per group using MODULE-LEVEL
VARIABLES (NOT a groupAccumulator parameter — that belongs to ROLLUP, not DENORMALIZER).

  append()  — NO parameters. Called ONCE PER INPUT RECORD.
    - $in.0.* IS accessible here. Read input fields and accumulate into module-level vars.
    - Returns OK/positive = continue; negative = error.

  transform()  — NO parameters. Called ONCE after all append() calls for the group.
    - $out.0.* IS accessible here.
    - $in.0.* is UNDEFINED here. CloverDX may expose the last appended record as an
      implementation detail, but the contract forbids relying on it.
    - Must emit ONLY from module-level variables populated during append().

  clean()  — Called after transform(). Reset all module-level variables.
    - Neither $in.0.* nor $out.0.* is accessible here.

### Evaluation rules for DENORMALIZER
- Any $in.0.field reference inside transform() → verdict="incorrect",
  failure_modes=["denormalizer_lifecycle"].
  EVEN IF exec_level=L3_pass: single-record-per-group test data silently masks this
  bug (last record == only record, so $in.0 appears to work). The code will produce
  wrong results for any group with more than one record.
- groupAccumulator parameter on append() or transform() → verdict="incorrect",
  failure_modes=["wrong_function_name"]. That parameter style belongs to ROLLUP.
- verdict="correct" only when transform() emits exclusively from module-level
  variables that were fully populated during append().
"""

_JUDGE_ROLLUP_NOTE = """\

## ROLLUP component contract

ROLLUP uses a TYPED groupAccumulator record parameter for group state. All five functions
are MANDATORY — missing any one aborts with "Required function(s) … are missing!".

  initGroup(TYPE groupAccumulator)  — First record of each group.
    $in.0 accessible. Initialize accumulator fields here.

  updateGroup(TYPE groupAccumulator) → boolean  — Every record.
    $in.0 accessible. Returns true → call updateTransform(); false → skip it.

  updateTransform(integer counter, TYPE groupAccumulator) → integer  — Per-record emit.
    Called after each updateGroup()=true. counter is 0-based.
    $in.0 AND $out.N accessible. Return SKIP to suppress this record's output.

  finishGroup(TYPE groupAccumulator) → boolean  — After last record.
    $in.0 accessible. Returns true → call transform(); false → skip group output.

  transform(integer counter, TYPE groupAccumulator) → integer  — Per-group emit.
    Called after finishGroup()=true. counter is 0-based.
    $in.0 (last record of group) AND $out.N accessible. Return SKIP to skip.

### Evaluation rules for ROLLUP
- rollup_missing_update_transform: updateTransform() absent → always incorrect.
  It must be present even if unused; give it `return SKIP;`.
- rollup_lifecycle: confusing per-record emit (updateTransform) with per-group emit
  (transform), or omitting initGroup reset.
- rollup_accumulator_mismatch: accumulator field names in CTL do not match the
  accumulator metadata record schema → runtime "Field not found" errors.
- rollup_per_record_emission: emitting from transform() on every counter value
  instead of only counter==0, producing duplicate group-summary rows.
"""

_JUDGE_NORMALIZER_NOTE = """\

## NORMALIZER component contract

NORMALIZER expands one input record into N output records. Module-level variables
bridge count() and transform(idx).

  count() → integer  — Called ONCE PER INPUT RECORD.
    $in.0.* accessible here. Compute and return N (number of output rows for this record).
    Return 0 to skip the record (transform() not called).
    Typically parses/caches a list into a module-level variable for transform() to index.

  transform(integer idx) → integer  — Called N times per input record (idx 0..N-1).
    $in.0.* AND $out.0.* accessible here. Emit one output row per call. idx is 0-based.

  clean()  — Called after the last transform() for each input record.
    Neither $in.0.* nor $out.0.* is accessible here. Reset module-level variables.

### Evaluation rules for NORMALIZER
- normalizer_count_transform_mismatch: count() returns N but transform() accesses
  indices ≥ N, or the module-level list has a different length than count() returns.
- normalizer_idx_off_by_one: accessing parts[idx+1] or parts[idx-1] instead of
  parts[idx], or returning length(parts)+1 from count().
- Reading $in.0.* inside clean() is a contract violation (unreliable; $in.0 is gone).
"""

_JUDGE_DATAGEN_NOTE = """\

## DATA_GENERATOR special rule
This candidate implements a DATA_GENERATOR component, which produces records using
random / sequence functions. The golden output was captured from ONE specific run —
any correct implementation will produce DIFFERENT random values each run.

exec_level=L3_mismatch is THEREFORE EXPECTED and does NOT by itself mean the code is wrong.

### Evaluation order for DATA_GENERATOR

1. **Requirement coverage (primary)** — read the user prompt for every stated business rule
   and check whether the CTL code satisfies each one:
   - Correct field assignments (right field names, right types)?
   - Value constraints respected (ranges, rounding, date bounds, string formats)?
   - Record count matches what was asked for (use tracking output_count)?
   - Return value of generate() is OK (0) — not a non-zero error code?
   A missing or wrong implementation of any stated rule → verdict="incorrect" even if the
   code compiles and runs.

2. **Execution sanity** — only after requirement coverage is assessed:
   - L1_fail / L2_fail → verdict="incorrect" regardless of code reading.
   - FINISHED_OK with correct record count → supports "correct" (combined with step 1).

3. **Structural checks**:
   - Entry point `function integer generate()` present.
   - All output fields from the schema populated.
   - No datagen_wrong_return_code or datagen_record_count_mismatch.

If all three levels pass → verdict="correct" even with L3_mismatch.
Prose / explanation style is irrelevant for DATA_GENERATOR correctness.
"""


def infer_component_type(text: str) -> str:
    """Infer component type from CTL function signatures.

    Used as a fallback when the setup-agent classification is unavailable (e.g. setup
    failed).  Ordered from most-specific signature to least-specific so early matches
    don't shadow later ones.

    Returns one of the canonical TYPE strings or "" when nothing matches.
    """
    # ROLLUP: only component with initGroup
    if re.search(r"function\s+\w+\s+initGroup\s*\(", text, re.IGNORECASE):
        return "ROLLUP"
    # PARTITION: getOutputPort
    if re.search(r"function\s+integer\s+getOutputPort\s*\(", text, re.IGNORECASE):
        return "PARTITION"
    # DATA_GENERATOR: generate() with no args
    if re.search(r"function\s+integer\s+generate\s*\(\s*\)", text, re.IGNORECASE):
        return "DATA_GENERATOR"
    # NORMALIZER: count() returns N; transform takes (integer idx)
    if re.search(r"function\s+integer\s+count\s*\(\s*\)", text, re.IGNORECASE):
        return "NORMALIZER"
    # DENORMALIZER: append() with no args (distinct from list append())
    if re.search(r"function\s+integer\s+append\s*\(\s*\)", text, re.IGNORECASE):
        return "DENORMALIZER"
    if re.search(r"function\s+integer\s+transform\s*\(", text, re.IGNORECASE):
        # EXT_HASH_JOIN: transform() that reads $in.1.
        if re.search(r"\$in\.1\b", text):
            return "EXT_HASH_JOIN"
        return "REFORMAT"
    # EXT_FILTER: has //#CTL2 header but no function declarations at all
    if re.search(r"//#CTL2", text, re.IGNORECASE) and not re.search(r"\bfunction\b", text):
        return "EXT_FILTER"
    return ""


def _build_judge_system(component_type: str) -> str:
    """Return the judge system prompt, with CTL2 reference and component-specific notes."""
    ref = (_CTL2_REFERENCE + "\n\n---\n\n") if _CTL2_REFERENCE else ""
    base = _JUDGE_SYSTEM_BASE
    if component_type in ("DATA_GENERATOR", "DATAGEN"):
        base += _JUDGE_DATAGEN_NOTE
    elif component_type == "DENORMALIZER":
        base += _JUDGE_DENORMALIZER_NOTE
    elif component_type == "ROLLUP":
        base += _JUDGE_ROLLUP_NOTE
    elif component_type == "NORMALIZER":
        base += _JUDGE_NORMALIZER_NOTE
    return ref + base


_JUDGE_USER = """\
## Task

Component type: {component_type}

### System prompt:
{system}

### User prompt:
{prompt}

---

## Candidate CTL
```
{candidate}
```

---

## Execution Evidence

Exec level reached : {exec_level}
Run status         : {run_status}

### Log excerpt:
{log_excerpt}

### Tracking:
{tracking}

### Output diff vs golden:
{output_diff}
"""


# ---------------------------------------------------------------------------
# Judge client
# ---------------------------------------------------------------------------

def _resolve_key(configured: Optional[str], env_name: str) -> Optional[str]:
    """Return the API key, falling back to env if config value is unset or unexpanded."""
    if configured and not configured.startswith("${"):
        return configured
    return os.environ.get(env_name)


class JudgeClient:

    def __init__(self, cfg: dict):
        self._cfg = cfg
        self._llm = None
        self.total_tokens: int = 0

    def _get_llm(self):
        if self._llm is not None:
            return self._llm
        provider = self._cfg.get("provider", "anthropic")
        if provider == "anthropic":
            import anthropic
            key = _resolve_key(self._cfg.get("api_key"), "ANTHROPIC_API_KEY")
            self._llm = anthropic.Anthropic(api_key=key)
        elif provider == "openai":
            from openai import OpenAI
            key = _resolve_key(self._cfg.get("api_key"), "OPENAI_API_KEY")
            self._llm = OpenAI(api_key=key, base_url=self._cfg.get("base_url"))
        else:
            raise ValueError(f"Unknown judge provider: {provider!r}")
        return self._llm

    def _call(self, system: str, user_message: str) -> str:
        provider = self._cfg.get("provider", "anthropic")
        model = self._cfg.get("model", "claude-opus-4-20250514")
        llm = self._get_llm()

        if provider == "anthropic":
            resp = llm.messages.create(
                model=model,
                max_tokens=1024,
                temperature=0.0,
                system=system,
                messages=[{"role": "user", "content": user_message}],
            )
            self.total_tokens += resp.usage.input_tokens + resp.usage.output_tokens
            return resp.content[0].text
        else:
            kwargs: dict = {
                "model": model,
                "messages": [
                    {"role": "system", "content": system},
                    {"role": "user", "content": user_message},
                ],
            }
            # Some OpenAI models (e.g. terra tier) only allow default temperature.
            # Send temperature only when explicitly configured.
            temperature = self._cfg.get("temperature")
            if temperature is not None:
                kwargs["temperature"] = temperature

            # Support both legacy "reasoning_effort" and shorter "effort" config keys.
            effort = self._cfg.get("reasoning_effort", self._cfg.get("effort"))
            if effort:
                kwargs["reasoning_effort"] = effort

            resp = llm.chat.completions.create(**kwargs)
            if resp.usage:
                self.total_tokens += resp.usage.prompt_tokens + resp.usage.completion_tokens
            return resp.choices[0].message.content or ""

    def judge(
        self,
        system: Optional[str],
        prompt: str,
        candidate_text: str,
        exec_level: str,
        run_status: str,
        log_excerpt: str,
        tracking: dict,
        output_diff: str,
        component_type: str = "",
        max_retries: int = 2,
    ) -> Optional[JudgeVerdict]:
        """
        Evaluate one candidate and return a JudgeVerdict, or None if the LLM
        consistently returns unparseable JSON.
        """
        # Resolve component type: use the setup-agent classification when available;
        # fall back to signature-based inference from the candidate text itself.
        effective_type = component_type or infer_component_type(candidate_text)
        judge_system = _build_judge_system(effective_type)
        user_msg = _JUDGE_USER.format(
            component_type=effective_type or "unknown",
            system=system or "(none)",
            prompt=prompt,
            candidate=candidate_text,
            exec_level=exec_level,
            run_status=run_status,
            log_excerpt=log_excerpt or "(none)",
            tracking=json.dumps(tracking, indent=2) if tracking else "(none)",
            output_diff=output_diff or "(none — output matched golden or not available)",
        )

        for attempt in range(max_retries):
            msg = user_msg
            if attempt > 0:
                msg += (
                    "\n\n**Respond with ONLY a single raw JSON object — "
                    "no markdown fences, no prose.**"
                )
            raw = self._call(judge_system, msg)
            verdict = _parse_verdict(raw, exec_level)
            if verdict is not None:
                return verdict
            if attempt == 0:
                print("[judge] Invalid JSON on attempt 1, retrying…")

        print("[judge] Could not parse verdict after retries — dropping candidate")
        return None


def _parse_verdict(raw: str, exec_level: str) -> Optional[JudgeVerdict]:
    # Strip thinking tokens
    raw = re.sub(r"<think(?:ing)?>[\s\S]*?</think(?:ing)?>", "", raw, flags=re.IGNORECASE).strip()
    # Strip markdown fences
    raw = re.sub(r"^```(?:json)?\s*", "", raw, flags=re.MULTILINE)
    raw = re.sub(r"```\s*$", "", raw, flags=re.MULTILINE).strip()

    data = None
    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        m = re.search(r"\{[\s\S]+\}", raw)
        if m:
            try:
                data = json.loads(m.group())
            except json.JSONDecodeError:
                pass
    if data is None:
        return None

    modes = [
        (m if m in FAILURE_MODES else "other")
        for m in (data.get("failure_modes") or [])
    ]

    return JudgeVerdict(
        verdict=data.get("verdict", "incorrect"),
        confidence=float(data.get("confidence", 0.5)),
        failure_modes=modes,
        explanation=data.get("explanation", ""),
        minimal_fix=data.get("minimal_fix", ""),
        exec_level=exec_level,
    )
